apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pd5y5n5pq-nodejs
  janus-idp.io/tekton: pd5y5n5pq-nodejs
  backstage.io/kubernetes-id: pd5y5n5pq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pd5y5n5pq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
