apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pd5y5n5pq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pd5y5n5pq-nodejs 
  name: pd5y5n5pq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pd5y5n5pq-nodejs 
