apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pd5y5n5pq-nodejs-gitops
  description: This is GitOps manifest for pd5y5n5pq-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=pd5y5n5pq-nodejs
    backstage.io/kubernetes-id: pd5y5n5pq-nodejs 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: pd5y5n5pq-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:pd5y5n5pq-nodejs
